### PR TITLE
4.5.0 add AppBar and Toolbar components

### PR DESCRIPTION
**Pull request by vikigenius**
Updated version to 4.5.0 and added entry to CHANGELOG: See https://github.com/StratoDem/sd-material-ui/pull/692

### CODE REVIEW

**Comment by vikigenius** [comment]
Also, just for clarity, I am working on a Dashboard and using sd-material-ui, so most likely am going to port more components as needed. Would you be interested in adding those as well?

**Comment by coralvanda** [comment]
> Also, just for clarity, I am working on a Dashboard and using sd-material-ui, so most likely am going to port more components as needed. Would you be interested in adding those as well?

Yes! We would be glad for any additional contributions you'd like to make.

**Review by coralvanda — CHANGES_REQUESTED** [review]
I think you also need to rerun the build scripts so this new version number is added to the auto-generated files. Otherwise, this looks good.

**Comment by vikigenius** [comment]
@coralvanda wdym? I ran `npm run build:all` is that not enough?

**Comment by coralvanda** [comment]
That was my bad. I misread the filenames that were changed and thought one was missing.

**Review by coralvanda — APPROVED** [review]

**Pull request merged**
